baseURL = "http://example.com/"
languageCode = "en-us"
title = "Mozakarat"
theme = "minimal"
googleAnalytics = ""

[params]
    author = "Omar"
    description = "A story of what I've learnt"
    githubUsername = "3mard"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:o@o-m.dev"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/3mard/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/_3mard/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/3mard/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.stackoverflow.com/users/18771050/3mard"
    name = "stack-overflow"
    weight = 5
