baseURL = 'http://o-m.dev'
languageCode = 'en-us'
title = '/home/3mar'
theme = 'hugo-paper'

[params]
  # color style
  color = 'light'                 # linen, wheat, gray, light

  # header social icons
  twitter = '_3mard1'
  github = '3mard'
  rss = true                      # show rss icon with link

  # home page profile
  avatar = '/avatar.png'
  name = "HI!; I'm Omar"
  bio = 'Mostly about computers, Sometimes about food!'

  # misc
  disableHLJS = false              # disable requesting highlight.js
  monoDarkIcon = false             # show monochrome dark mode icon